---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
- name: jumpbox-deployment
- name: stemcell

outputs:
- name: updated-jumpbox-deployment

params:
  IAAS:

run:
  path: jumpbox-deployment/ci/tasks/bump-stemcell.sh
