---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfinfrastructure/deployment

inputs:
- name: jumpbox-deployment
- name: stemcell-azure

outputs:
- name: updated-jumpbox-deployment

run:
  path: jumpbox-deployment/ci/tasks/bump-stemcell.sh
